spring.application.name=appsembly

#logging.level.dateformat=hh:mm
spring.main.banner-mode=off
spring.thymeleaf.cache=off
spring.thymeleaf.mode=HTML

# Configuración de PostgreSQL
server.address=0.0.0.0
server.port=${SERVER_PORT:8080}
server.forward-headers-strategy=framework
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appsembly}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false

spring.security.user.name=edward
spring.security.user.password=12345

# JWT Config
jwt.secret.key=68218aaefb128e7999170d8ece1d9776411b50bca62331e76b1717d141a15a7f
jwt.time.expiration=86400000